server:
  port: 8761

spring:
  application:
    name: eureka-server
eureka:
  name: eureka-server
  enableSelfPreservation: true
  server:
    renewalPercentThreshold: 0.33
  client:
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost